FROM node

ENV NPM_CONFIG_LOGLEVEL warn

RUN mkdir -p /frontend
WORKDIR /frontend
COPY ./frontend ./

RUN npm install

# Build and optimize react app
RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]
