# Generated by Django 2.0.1 on 2018-02-01 21:17

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(api.models.Employee.get_default_supervisor), to='api.Employee'),
        ),
    ]
